/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import javax.swing.JFrame;

/**
 *
 * @author win10pro
 */
public class MainMenuFrame extends javax.swing.JFrame {

    /**
     * Creates new form MainFrame
     */
    public MainMenuFrame() {
        initComponents();
        this.setLocationRelativeTo(null);
        this.setDefaultCloseOperation(JFrame.HIDE_ON_CLOSE);
        this.setExtendedState(JFrame.MAXIMIZED_BOTH);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        desktopPane = new javax.swing.JDesktopPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        btnLog = new javax.swing.JMenuItem();
        btnExit = new javax.swing.JMenuItem();
        PM_Frame_Menu = new javax.swing.JMenu();
        PF_Menu_CustomerM = new javax.swing.JMenuItem();
        PF_Menu_MechanicM = new javax.swing.JMenuItem();
        CE_Frame_Menu = new javax.swing.JMenu();
        CF_Menu_BrandM = new javax.swing.JMenuItem();
        CF_Menu_CarSupplierM = new javax.swing.JMenuItem();
        CF_Menu_CarPartM = new javax.swing.JMenuItem();
        BR_Frame_Menu = new javax.swing.JMenu();
        BF_Menu_BookingM = new javax.swing.JMenuItem();
        BF_Menu_RequirementM = new javax.swing.JMenuItem();
        R_FrameMenu = new javax.swing.JMenu();
        RF_Menu_Report = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Car Manager");

        desktopPane.setToolTipText("");
        desktopPane.setPreferredSize(new java.awt.Dimension(1000, 1000));

        javax.swing.GroupLayout desktopPaneLayout = new javax.swing.GroupLayout(desktopPane);
        desktopPane.setLayout(desktopPaneLayout);
        desktopPaneLayout.setHorizontalGroup(
            desktopPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1000, Short.MAX_VALUE)
        );
        desktopPaneLayout.setVerticalGroup(
            desktopPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1000, Short.MAX_VALUE)
        );

        jMenu1.setText("Menu");

        btnLog.setText("Login/Logout");
        jMenu1.add(btnLog);

        btnExit.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F4, java.awt.event.InputEvent.ALT_MASK));
        btnExit.setText("Exit");
        btnExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExitActionPerformed(evt);
            }
        });
        jMenu1.add(btnExit);

        jMenuBar1.add(jMenu1);

        PM_Frame_Menu.setText("Personal Management");

        PF_Menu_CustomerM.setText("Customer Management");
        PF_Menu_CustomerM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PF_Menu_CustomerMActionPerformed(evt);
            }
        });
        PM_Frame_Menu.add(PF_Menu_CustomerM);

        PF_Menu_MechanicM.setText("Mechanic Management");
        PF_Menu_MechanicM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PF_Menu_MechanicMActionPerformed(evt);
            }
        });
        PM_Frame_Menu.add(PF_Menu_MechanicM);

        jMenuBar1.add(PM_Frame_Menu);

        CE_Frame_Menu.setText("Car Equipment");

        CF_Menu_BrandM.setText("Car Brand");
        CF_Menu_BrandM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CF_Menu_BrandMActionPerformed(evt);
            }
        });
        CE_Frame_Menu.add(CF_Menu_BrandM);

        CF_Menu_CarSupplierM.setText("Car Equipment Supplier");
        CF_Menu_CarSupplierM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CF_Menu_CarSupplierMActionPerformed(evt);
            }
        });
        CE_Frame_Menu.add(CF_Menu_CarSupplierM);

        CF_Menu_CarPartM.setText("Car Part Info");
        CF_Menu_CarPartM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CF_Menu_CarPartMActionPerformed(evt);
            }
        });
        CE_Frame_Menu.add(CF_Menu_CarPartM);

        jMenuBar1.add(CE_Frame_Menu);

        BR_Frame_Menu.setText("Booking & Requirement");

        BF_Menu_BookingM.setText("Booking");
        BF_Menu_BookingM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BF_Menu_BookingMActionPerformed(evt);
            }
        });
        BR_Frame_Menu.add(BF_Menu_BookingM);

        BF_Menu_RequirementM.setText("Requirement");
        BF_Menu_RequirementM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BF_Menu_RequirementMActionPerformed(evt);
            }
        });
        BR_Frame_Menu.add(BF_Menu_RequirementM);

        jMenuBar1.add(BR_Frame_Menu);

        R_FrameMenu.setText("Report");

        RF_Menu_Report.setText("Report");
        RF_Menu_Report.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RF_Menu_ReportActionPerformed(evt);
            }
        });
        R_FrameMenu.add(RF_Menu_Report);

        jMenuBar1.add(R_FrameMenu);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(desktopPane, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(desktopPane, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExitActionPerformed
        System.exit(0);
    }//GEN-LAST:event_btnExitActionPerformed

    private void PF_Menu_CustomerMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PF_Menu_CustomerMActionPerformed
        CustomerFrame customer = new CustomerFrame();
        customer.setVisible(true);
    }//GEN-LAST:event_PF_Menu_CustomerMActionPerformed

    private void CF_Menu_BrandMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CF_Menu_BrandMActionPerformed
        BrandFrame brand = new BrandFrame();
        brand.setVisible(true);
    }//GEN-LAST:event_CF_Menu_BrandMActionPerformed

    private void BF_Menu_BookingMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BF_Menu_BookingMActionPerformed
        BookingFrame booking = new BookingFrame();
        booking.setVisible(true);
    }//GEN-LAST:event_BF_Menu_BookingMActionPerformed

    private void BF_Menu_RequirementMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BF_Menu_RequirementMActionPerformed
        RequirementFrame requirement = new RequirementFrame();
        requirement.setVisible(true);
    }//GEN-LAST:event_BF_Menu_RequirementMActionPerformed

    private void PF_Menu_MechanicMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PF_Menu_MechanicMActionPerformed
        MechanicFrame mechanic = new MechanicFrame();
        mechanic.setVisible(true);
    }//GEN-LAST:event_PF_Menu_MechanicMActionPerformed

    private void CF_Menu_CarSupplierMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CF_Menu_CarSupplierMActionPerformed
        SupplierFrame supplier = new SupplierFrame();
        supplier.setVisible(true);
    }//GEN-LAST:event_CF_Menu_CarSupplierMActionPerformed

    private void CF_Menu_CarPartMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CF_Menu_CarPartMActionPerformed
        PartFrame part = new PartFrame();
        part.setVisible(true);
    }//GEN-LAST:event_CF_Menu_CarPartMActionPerformed

    private void RF_Menu_ReportActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RF_Menu_ReportActionPerformed
        ReportFrame reportbook = new ReportFrame();
        reportbook.setVisible(true);
    }//GEN-LAST:event_RF_Menu_ReportActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainMenuFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainMenuFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainMenuFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainMenuFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainMenuFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem BF_Menu_BookingM;
    private javax.swing.JMenuItem BF_Menu_RequirementM;
    private javax.swing.JMenu BR_Frame_Menu;
    private javax.swing.JMenu CE_Frame_Menu;
    private javax.swing.JMenuItem CF_Menu_BrandM;
    private javax.swing.JMenuItem CF_Menu_CarPartM;
    private javax.swing.JMenuItem CF_Menu_CarSupplierM;
    private javax.swing.JMenuItem PF_Menu_CustomerM;
    private javax.swing.JMenuItem PF_Menu_MechanicM;
    private javax.swing.JMenu PM_Frame_Menu;
    private javax.swing.JMenuItem RF_Menu_Report;
    private javax.swing.JMenu R_FrameMenu;
    private javax.swing.JMenuItem btnExit;
    private javax.swing.JMenuItem btnLog;
    private javax.swing.JDesktopPane desktopPane;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    // End of variables declaration//GEN-END:variables
}
