/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import java.util.ArrayList;
import java.util.InputMismatchException;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;
import ws.CarWebService;
import ws.CarWebService_Service;
import ws.MechanicDBO;

/**
 *
 * @author mrkho
 */
public class MechanicFrame extends javax.swing.JFrame {
    
    private CarWebService_Service carServices;
    private CarWebService port;
    /**
     * Creates new form SourceFrame
     */
    public MechanicFrame() {
        carServices = new CarWebService_Service();
        port = carServices.getCarWebServicePort();
        
        initComponents();
        loadAllMechanic();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        rdSearchSource = new javax.swing.ButtonGroup();
        jScrollPane1 = new javax.swing.JScrollPane();
        listMechanic = new javax.swing.JList<>();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtSearch = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtMechanicID = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        txtMechanicName = new javax.swing.JTextField();
        btnAdd = new javax.swing.JButton();
        btnUpdate = new javax.swing.JButton();
        btnDelete = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        rdMechanicID = new javax.swing.JRadioButton();
        rdMechanicName = new javax.swing.JRadioButton();
        jLabel5 = new javax.swing.JLabel();
        btnBackToMainMenu = new javax.swing.JButton();
        txtMechanicAddress = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txtMechanicPhone = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        listMechanic.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                listMechanicValueChanged(evt);
            }
        });
        jScrollPane1.setViewportView(listMechanic);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setText("Search");

        jLabel3.setText("Mechanic ID");

        txtSearch.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtSearchKeyPressed(evt);
            }
        });

        jLabel4.setText("Mechanic Name");

        btnAdd.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnAdd.setText("Add");
        btnAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddActionPerformed(evt);
            }
        });

        btnUpdate.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnUpdate.setText("Update");
        btnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateActionPerformed(evt);
            }
        });

        btnDelete.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnDelete.setText("Delete");
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Bodoni MT", 3, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Mechanic Management");

        rdSearchSource.add(rdMechanicID);
        rdMechanicID.setText("Mechanic ID");

        rdSearchSource.add(rdMechanicName);
        rdMechanicName.setText("Mechanic Name");

        jLabel5.setText("Mechanic Address");

        btnBackToMainMenu.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnBackToMainMenu.setText("Back To Menu");
        btnBackToMainMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackToMainMenuActionPerformed(evt);
            }
        });

        jLabel6.setText("Mechanic Phone");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator1)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 267, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(btnAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(btnUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(btnDelete, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(0, 0, Short.MAX_VALUE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel3)
                                            .addComponent(jLabel4)
                                            .addComponent(jLabel5)
                                            .addComponent(jLabel6))
                                        .addGap(12, 12, 12)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(txtMechanicPhone)
                                            .addComponent(txtMechanicName, javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(txtMechanicAddress)
                                            .addComponent(txtMechanicID)))))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(43, 43, 43)
                                .addComponent(rdMechanicID, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(rdMechanicName)
                                .addGap(0, 61, Short.MAX_VALUE))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(btnBackToMainMenu, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(41, 41, 41)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnBackToMainMenu, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 44, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtSearch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(rdMechanicID)
                    .addComponent(rdMechanicName))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(5, 5, 5)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1)
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(txtMechanicID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(14, 14, 14)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtMechanicName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4))
                        .addGap(17, 17, 17)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtMechanicPhone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6))
                        .addGap(14, 14, 14)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(txtMechanicAddress, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 63, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnAdd)
                            .addComponent(btnUpdate)
                            .addComponent(btnDelete))
                        .addGap(72, 72, 72))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtSearchKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtSearchKeyPressed
        if (evt.getKeyCode() == 10) { //enter is pressed
            if (rdMechanicID.isSelected()) {
                searchByMechanicID();
            } else {
                searchByMechanicName();
            }
        }
    }//GEN-LAST:event_txtSearchKeyPressed

    private void btnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddActionPerformed
        if(checkInputValue()){
            String mechanicID = txtMechanicID.getText();
            String mechanicName = txtMechanicName.getText();
            String mechanicPhone = txtMechanicPhone.getText();
            String mechanicAddress = txtMechanicAddress.getText();
            String add = port.insertMechanic(mechanicID, mechanicName, mechanicPhone, mechanicAddress);
            JOptionPane.showMessageDialog(rootPane, add);
            //refresh listbox to update data from database
            loadAllMechanic();
        }
    }//GEN-LAST:event_btnAddActionPerformed

    private void btnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateActionPerformed
        if(listMechanic.getSelectedIndex() !=-1){
            if(checkInputValue()){
                String mechanicID = txtMechanicID.getText();
                String mechanicName = txtMechanicName.getText();
                String mechanicPhone = txtMechanicPhone.getText();
                String mechanicAddress = txtMechanicAddress.getText();
                String update = port.updateMechanic(mechanicID, mechanicName, mechanicPhone, mechanicAddress);
                JOptionPane.showMessageDialog(rootPane, update);
                loadAllMechanic();
            }
        }
        else
            JOptionPane.showMessageDialog(rootPane, "Please select a mechanic");
    }//GEN-LAST:event_btnUpdateActionPerformed

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
        if(listMechanic.getSelectedIndex() != -1){
            String mechanicID = txtMechanicID.getText();
            String delete = port.deleteMechanic(mechanicID);
            JOptionPane.showMessageDialog(rootPane, delete);
            loadAllMechanic();
        }
        else
            JOptionPane.showMessageDialog(rootPane, "Please select a mechanic");
    }//GEN-LAST:event_btnDeleteActionPerformed

    private void listMechanicValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_listMechanicValueChanged
        if(listMechanic.getSelectedIndex() != -1){
            MechanicDBO mechanic = listMechanic.getSelectedValue();
            txtMechanicID.setText(mechanic.getMechanicID());
            txtMechanicName.setText(mechanic.getMechanicName());
            txtMechanicPhone.setText(mechanic.getMechanicPhoneNumber());
            txtMechanicAddress.setText(mechanic.getMechanicAddress());
        }
    }//GEN-LAST:event_listMechanicValueChanged

    private void btnBackToMainMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackToMainMenuActionPerformed
        MainMenuFrame mainFrame = new MainMenuFrame();
        mainFrame.setVisible(true);
    }//GEN-LAST:event_btnBackToMainMenuActionPerformed
    private void searchByMechanicID() {
        String mechanicID = txtSearch.getText();
        if (!getValidNumber(mechanicID)) {
            loadAllMechanic();
        } else {
            ArrayList<MechanicDBO> mechanic = (ArrayList<MechanicDBO>) port.getMechanicByID(mechanicID);
            DefaultListModel<MechanicDBO> defaultModel = new DefaultListModel<>();

            for (MechanicDBO mec : mechanic) {
                defaultModel.addElement(mec);
            }

            listMechanic.setModel(defaultModel);
        }
    }

    private void searchByMechanicName() {
        String mechanicName = txtSearch.getText();
        if (mechanicName.equals("")) {
            loadAllMechanic();
        } else {
            ArrayList<MechanicDBO> mechanic = (ArrayList<MechanicDBO>) port.getMechanicByName(mechanicName);
            DefaultListModel<MechanicDBO> defaultModel = new DefaultListModel<>();
            
            for (MechanicDBO mec : mechanic) {
                defaultModel.addElement(mec);
            }

            listMechanic.setModel(defaultModel);
        }
    }
    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdd;
    private javax.swing.JButton btnBackToMainMenu;
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnUpdate;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JList<MechanicDBO> listMechanic;
    private javax.swing.JRadioButton rdMechanicID;
    private javax.swing.JRadioButton rdMechanicName;
    private javax.swing.ButtonGroup rdSearchSource;
    private javax.swing.JTextField txtMechanicAddress;
    private javax.swing.JTextField txtMechanicID;
    private javax.swing.JTextField txtMechanicName;
    private javax.swing.JTextField txtMechanicPhone;
    private javax.swing.JTextField txtSearch;
    // End of variables declaration//GEN-END:variables
    private void loadAllMechanic() {
        ArrayList<MechanicDBO> mechanic = (ArrayList<MechanicDBO>) port.getAllMechanic();
        DefaultListModel<MechanicDBO> defaultModel = new DefaultListModel<>();

        for (MechanicDBO mec : mechanic) {
            defaultModel.addElement(mec);
        }

        listMechanic.setModel(defaultModel);
    }
    
    public boolean checkInputValue() {
        String mechanicID = txtMechanicID.getText();
        if (!getValidNumber(mechanicID)) {
            JOptionPane.showMessageDialog(rootPane, " mechanicID is not null value and must be numeric!)");
            return false;
        }
        try {
            String mechanicName = txtMechanicName.getText();
            if (getValidString(mechanicName) == true) {
            } else {
                JOptionPane.showMessageDialog(rootPane, " Mechanic name is not null value & Author name isn't containts numbers. Please input name of mechanic correctly");
                return false;
            }
        } catch (InputMismatchException ea) {
                JOptionPane.showMessageDialog(rootPane, " Mechanic name isn't containts numbers. Please input name of mechanic correctly");
        }
        String mechanicPhone = txtMechanicPhone.getText();
        // Tạo đối tượng Pattern
        Pattern pattern = Pattern.compile(mechanicPhone);
        // Lấy ra đối tượng Matcher
        Matcher matcher = pattern.matcher("\\d{9,11}");
        boolean checkPhone = matcher.matches();
        if (checkPhone) {
            JOptionPane.showMessageDialog(rootPane, " Mechanic Phone is not null value and must be numeric (9 to 11 numbers)");
            return false;
        }
        return true;
    }

    public static boolean getValidNumber(String str1) {
        return str1.matches("\\d+");
    }

    public static boolean getValidString(String str2) {
        return str2.matches("\\D+");
    }
}
