/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import java.util.ArrayList;
import java.util.InputMismatchException;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;
import ws.CarWebService;
import ws.CarWebService_Service;
import ws.SupplierDBO;

/**
 *
 * @author mrkho
 */
public class SupplierFrame extends javax.swing.JFrame {
    
    private CarWebService_Service carServices;
    private CarWebService port;
    /**
     * Creates new form SourceFrame
     */
    public SupplierFrame() {
        carServices = new CarWebService_Service();
        port = carServices.getCarWebServicePort();
        
        initComponents();
        loadAllSupplier();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        rdSearchSource = new javax.swing.ButtonGroup();
        jScrollPane1 = new javax.swing.JScrollPane();
        listSupplier = new javax.swing.JList<>();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtSearch = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtSupplierID = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        txtSupplierName = new javax.swing.JTextField();
        btnAdd = new javax.swing.JButton();
        btnUpdate = new javax.swing.JButton();
        btnDelete = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        rdSupplierID = new javax.swing.JRadioButton();
        rdSupplierName = new javax.swing.JRadioButton();
        jLabel5 = new javax.swing.JLabel();
        btnBackToMainMenu = new javax.swing.JButton();
        txtSupplierAddress = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txtSupplierPhone = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        listSupplier.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                listSupplierValueChanged(evt);
            }
        });
        jScrollPane1.setViewportView(listSupplier);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setText("Search");

        jLabel3.setText("Supplier ID");

        txtSearch.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtSearchKeyPressed(evt);
            }
        });

        jLabel4.setText("Supplier Name");

        btnAdd.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnAdd.setText("Add");
        btnAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddActionPerformed(evt);
            }
        });

        btnUpdate.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnUpdate.setText("Update");
        btnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateActionPerformed(evt);
            }
        });

        btnDelete.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnDelete.setText("Delete");
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Bodoni MT", 3, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Supplier Management");

        rdSearchSource.add(rdSupplierID);
        rdSupplierID.setText("Supplier ID");

        rdSearchSource.add(rdSupplierName);
        rdSupplierName.setText("Supplier Name");

        jLabel5.setText("Supplier Address");

        btnBackToMainMenu.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnBackToMainMenu.setText("Back To Menu");
        btnBackToMainMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackToMainMenuActionPerformed(evt);
            }
        });

        jLabel6.setText("Supplier Phone ");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator1)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 267, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel3)
                                            .addComponent(jLabel4)
                                            .addComponent(jLabel5))
                                        .addGap(12, 12, 12)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(txtSupplierName, javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(txtSupplierAddress)
                                            .addComponent(txtSupplierID)))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(btnAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(btnUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(btnDelete, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(0, 0, Short.MAX_VALUE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel6)
                                        .addGap(18, 18, 18)
                                        .addComponent(txtSupplierPhone))))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(43, 43, 43)
                                .addComponent(rdSupplierID, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(rdSupplierName)
                                .addGap(0, 67, Short.MAX_VALUE))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(btnBackToMainMenu, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(41, 41, 41)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnBackToMainMenu, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 44, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtSearch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(rdSupplierID)
                    .addComponent(rdSupplierName))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(5, 5, 5)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1)
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(txtSupplierID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(14, 14, 14)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtSupplierName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4))
                        .addGap(14, 14, 14)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(txtSupplierAddress, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(14, 14, 14)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(txtSupplierPhone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 66, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnAdd)
                            .addComponent(btnUpdate)
                            .addComponent(btnDelete))
                        .addGap(72, 72, 72))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtSearchKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtSearchKeyPressed
        if (evt.getKeyCode() == 10) { //enter is pressed
            if (rdSupplierID.isSelected()) {
                searchBySupplierID();
            } else {
                searchBySupplierName();
            }
        }
    }//GEN-LAST:event_txtSearchKeyPressed

    private void btnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddActionPerformed
        if(checkInputValue()){    
            String supplierID = txtSupplierID.getText();
            String supplierName = txtSupplierName.getText();
            String supplierAddress = txtSupplierAddress.getText();
            String supplierPhone = txtSupplierPhone.getText();
            String add = port.insertSupplier(supplierID, supplierName, supplierAddress, supplierPhone);
            JOptionPane.showMessageDialog(rootPane, add);
            //refresh listbox to update data from database
            loadAllSupplier();
        }
    }//GEN-LAST:event_btnAddActionPerformed

    private void btnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateActionPerformed
        if(listSupplier.getSelectedIndex() !=-1){
            if(checkInputValue()){    
                String supplierID = txtSupplierID.getText();
                String supplierName = txtSupplierName.getText();
                String supplierAddress = txtSupplierAddress.getText();
                String supplierPhone = txtSupplierPhone.getText();
                String update = port.updateSupplier(supplierID, supplierName, supplierAddress, supplierPhone);
                JOptionPane.showMessageDialog(rootPane, update);
                loadAllSupplier();
            }
        }
        else
            JOptionPane.showMessageDialog(rootPane, "Please select a supplier");
    }//GEN-LAST:event_btnUpdateActionPerformed

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
        if(listSupplier.getSelectedIndex() != -1){
            String supplierID = txtSupplierID.getText();
            String delete = port.deleteSupplier(supplierID);
            JOptionPane.showMessageDialog(rootPane, delete);
            loadAllSupplier();
        }
        else
            JOptionPane.showMessageDialog(rootPane, "Please select a brand");
    }//GEN-LAST:event_btnDeleteActionPerformed

    private void listSupplierValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_listSupplierValueChanged
        if(listSupplier.getSelectedIndex() != -1){
            SupplierDBO supplier = listSupplier.getSelectedValue();
            txtSupplierID.setText(supplier.getSupplierID() + "");
            txtSupplierName.setText(supplier.getSupplierName());
            txtSupplierAddress.setText(supplier.getSupplierAddress());
            txtSupplierPhone.setText(supplier.getSupplierPhone() + "");
        }
    }//GEN-LAST:event_listSupplierValueChanged

    private void btnBackToMainMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackToMainMenuActionPerformed
        MainMenuFrame mainFrame = new MainMenuFrame();
        mainFrame.setVisible(true);
    }//GEN-LAST:event_btnBackToMainMenuActionPerformed
    private void searchBySupplierID() {
        String supplierID = txtSearch.getText();
        if(!getValidNumber(supplierID)){
            loadAllSupplier();
        }
        else {
            ArrayList<SupplierDBO> supplier = (ArrayList<SupplierDBO>) port.getSupplierByID(supplierID);
            DefaultListModel<SupplierDBO> defaultModel = new DefaultListModel<>();

            for (SupplierDBO sup : supplier) {
                defaultModel.addElement(sup);
            }

            listSupplier.setModel(defaultModel);
        }
    }

    private void searchBySupplierName() {
        String supplierName = txtSearch.getText();
        if (supplierName.equals("")) {
            loadAllSupplier();
        } else {
            ArrayList<SupplierDBO> supplier = (ArrayList<SupplierDBO>) port.getSupplierByName(supplierName);
            DefaultListModel<SupplierDBO> defaultModel = new DefaultListModel<>();
            
            for (SupplierDBO sup : supplier) {
                defaultModel.addElement(sup);
            }

            listSupplier.setModel(defaultModel);
        }
    }
    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdd;
    private javax.swing.JButton btnBackToMainMenu;
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnUpdate;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JList<SupplierDBO> listSupplier;
    private javax.swing.ButtonGroup rdSearchSource;
    private javax.swing.JRadioButton rdSupplierID;
    private javax.swing.JRadioButton rdSupplierName;
    private javax.swing.JTextField txtSearch;
    private javax.swing.JTextField txtSupplierAddress;
    private javax.swing.JTextField txtSupplierID;
    private javax.swing.JTextField txtSupplierName;
    private javax.swing.JTextField txtSupplierPhone;
    // End of variables declaration//GEN-END:variables
    private void loadAllSupplier() {
        ArrayList<SupplierDBO> supplier = (ArrayList<SupplierDBO>) port.getAllSupplier();
        DefaultListModel<SupplierDBO> defaultModel = new DefaultListModel<>();

        for (SupplierDBO sup : supplier) {
            defaultModel.addElement(sup);
        }

        listSupplier.setModel(defaultModel);
    }
    
    public boolean checkInputValue() {
        String supplierID = txtSupplierID.getText();
        if (!getValidNumber(supplierID)) {
            JOptionPane.showMessageDialog(rootPane, " supplierID is not null value and must be numeric!)");
            return false;
        }
        try {
            String supplierName = txtSupplierName.getText();
            if (getValidString(supplierName) == true) {
            } else {
                JOptionPane.showMessageDialog(rootPane, " Suppplier name is not null value & Author name isn't containts numbers. Please input name of supplier correctly");
                return false;
            }
        } catch (InputMismatchException ea) {
                JOptionPane.showMessageDialog(rootPane, " Suppplier name isn't containts numbers. Please input name of supplier correctly");
        }
        String supplierPhone = txtSupplierPhone.getText();
        // Tạo đối tượng Pattern
        Pattern pattern = Pattern.compile(supplierPhone);
        // Lấy ra đối tượng Matcher
        Matcher matcher = pattern.matcher("\\d{9,11}");
        boolean checkPhone = matcher.matches();
        if (checkPhone) {
            JOptionPane.showMessageDialog(rootPane, " Supplier Phone is not null value and must be numeric (9 to 11 numbers)");
            return false;
        }
        return true;
    }

    public static boolean getValidNumber(String str1) {
        return str1.matches("\\d+");
    }

    public static boolean getValidString(String str2) {
        return str2.matches("\\D+");
    }
}
